apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: react-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: react-app
        image: mykwetterdockeracr.azurecr.io/react-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31000
  selector:
    app: react-app