apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: accountservice
        image: mykwetterdockeracr.azurecr.io/accountservice
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8083
  selector:
    app: accountservice