apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileservice
spec:
  selector:
    matchLabels:
      app: profileservice
  replicas: 1
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
        - name: profileservice
          image: kevints98/profileservice
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi