apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: notificationservice
        image: mykwetterdockeracr.azurecr.io/notificationservice
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: notificationservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: notificationservice